[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html (so React Router / SPA works on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: set caching headers for static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
